cards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        "",
        views.CardListView.as_view(),
        name="card-list"
    ),
    path(
        "new",
        views.CardCreateView.as_view(),
        name="card-create"
    ),
    path(
        "edit/<int:pk>",
        views.CardUpdateView.as_view(),
        name="card-update"
    ),
    path(
        "box/<int:box_num>",
        views.BoxView.as_view(),
        name="box"
    )
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path(
        "",
        views.portfolio_index,
        name='portfolio_index'
    ),
    path(
        "<int:pk>/",
        views.portfolio_detail,
        name='portfolio_detail'
    ),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("todo_app.urls")),
    path("dinosoar/", include("dinofacts.urls")),
    path("cards/", include("cards.urls")),
    path("terms/", include("terms.urls")),
    path("feedback/", include("feedback.urls")),
    path("dwitter/", include("dwitter.urls")),
    path("portfolios/", include("portfolio.urls")),
    path('admin/', admin.site.urls),
]

portfolio/models.py
from django.db import models

# Create your models here.

class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path="/img")

portfolio/views.py
from django.shortcuts import render
from .models import Portfolio

# Create your views here.

def portfolio_index(request):
    portfolios = Portfolio.objects.all()
    context = {
        'portfolios': portfolios
    }
    return render(request, 'portfolio_index.html', context)

def portfolio_detail(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    context = {
        'portfolio': portfolio
    }
    return render(request, 'portfolio_detail.html', context)

portfolio/templates/portfolio_base.html
<!-- portfolio/templates/portfolio_base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Portfolios</title>
</head>
<body>
    <a href="{% url 'portfolio:portfolio_index' %} ">
        <section class="hero is-small is-success mb-4">
            <div class="hero-body">
                <h1 class="title is-1">Portfolios</h1>
                <p class="subtitle is-4">
                    Your tiny social network built with Django
                </p>
            </div>        
        </section>
    </a>
    
    <div class="container">
        <div class="columns">

            {% block content %}

            {% endblock content %}
            
        </div>        
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

portfolio/templates/portfolio_detail.html
{% extends "portfolio_base.html" %}
{% load static %}

{% block content %}
<h1>{{ portfolio.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static portfolio.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ portfolio.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ portfolio.technology }}</p>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio_index.html
{% extends "portfolio_base.html" %}

{% load static %}

{% block content %}

<div class="row">
    {% for portfolio in portfolios %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static portfolio.image %}" alt="Portfolio Image">
            <div class="card-body">
                <h5 class="card-title">{{ portfolio.title }}</h5>
                <p class="card-text">{{ portfolio.description }}</p>
                <a href="{% url 'portfolio:portfolio_detail' portfolio.pk %}"
                   class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}